spring.application.name=benefits


spring.datasource.url=jdbc:postgresql://localhost:5432/memberdb
spring.datasource.username=devuser
spring.datasource.password=devpass

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com

google.client.id=972231826627-m8prcdhvug72smfskigpnq667u2inp9k.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost:5173